export const BOOKS = [
  {
    id: 1,
    title: "Đắc Nhân Tâm",
    author: "Dale Carnegie",
    price: 86000,
    originalPrice: 120000,
    rating: 4.8,
    reviews: 1250,
    image: "/book-cover-dac-nhan-tam.jpg",
    category: "Kỹ năng sống",
    inStock: true,
    description:
      "Đắc nhân tâm của Dale Carnegie là quyển sách nổi tiếng nhất, bán chạy nhất và có tầm ảnh hưởng nhất của mọi thời đại.",
    pages: 320,
    publisher: "NXB Tổng Hợp TPHCM",
    publishDate: "2020-05-15",
    language: "Tiếng Việt",
    isbn: "978-604-2-17483-5",
    genres: ["Kỹ năng sống", "Tâm lý học", "Phát triển bản thân"],
  },
  {
    id: 2,
    title: "Nhà Giả Kim",
    author: "Paulo Coelho",
    price: 79000,
    originalPrice: 95000,
    rating: 4.9,
    reviews: 2100,
    image: "/book-cover-alchemist.png",
    category: "Văn học",
    inStock: true,
    description:
      "Tất cả những trải nghiệm trong chuyến phiêu du theo đuổi vận mệnh của mình đã giúp Santiago thấu hiểu được ý nghĩa sâu xa nhất của hạnh phúc.",
    pages: 227,
    publisher: "NXB Hội Nhà Văn",
    publishDate: "2013-12-01",
    language: "Tiếng Việt",
    isbn: "978-604-2-08872-8",
    genres: ["Văn học", "Tiểu thuyết", "Triết học"],
  },
  {
    id: 3,
    title: "Sapiens: Lược Sử Loài Người",
    author: "Yuval Noah Harari",
    price: 189000,
    originalPrice: 220000,
    rating: 4.7,
    reviews: 890,
    image: "/sapiens-book-cover.png",
    category: "Lịch sử",
    inStock: true,
    description: "Từ một sinh vật không đáng kể, bộ lạc Homo Sapiens đã vươn lên thống trị hành tinh này như thế nào?",
    pages: 512,
    publisher: "NXB Thế Giới",
    publishDate: "2018-03-20",
    language: "Tiếng Việt",
    isbn: "978-604-2-77824-3",
    genres: ["Lịch sử", "Khoa học", "Nhân học", "Triết học"],
  },
  {
    id: 4,
    title: "Tuổi Trẻ Đáng Giá Bao Nhiêu",
    author: "Rosie Nguyễn",
    price: 68000,
    originalPrice: 85000,
    rating: 4.6,
    reviews: 1560,
    image: "/book-cover-youth.jpg",
    category: "Kỹ năng sống",
    inStock: true,
    description: "Tuổi trẻ đáng giá bao nhiêu? là cuốn sách dành cho mọi lứa tuổi, đặc biệt là tuổi trẻ.",
    pages: 268,
    publisher: "NXB Hội Nhà Văn",
    publishDate: "2019-11-10",
    language: "Tiếng Việt",
    isbn: "978-604-2-56789-1",
    genres: ["Kỹ năng sống", "Phát triển bản thân", "Tuổi trẻ"],
  },
  {
    id: 5,
    title: "Atomic Habits",
    author: "James Clear",
    price: 142000,
    originalPrice: 180000,
    rating: 4.9,
    reviews: 3200,
    image: "/atomic-habits-cover.png",
    category: "Kỹ năng sống",
    inStock: true,
    description:
      "Dù bạn có mục tiêu là gì đi chăng nữa, Atomic Habits sẽ cung cấp cho bạn một khuôn khổ đã được chứng minh để cải thiện.",
    pages: 352,
    publisher: "NXB Thế Giới",
    publishDate: "2020-08-15",
    language: "Tiếng Việt",
    isbn: "978-604-2-99876-2",
    genres: ["Kỹ năng sống", "Tâm lý học", "Phát triển bản thân", "Thói quen"],
  },
  {
    id: 6,
    title: "Cà Phê Cùng Tony",
    author: "Tony Buổi Sáng",
    price: 95000,
    originalPrice: 110000,
    rating: 4.5,
    reviews: 780,
    image: "/book-cover-coffee-tony.jpg",
    category: "Kỹ năng sống",
    inStock: false,
    description: "Cà phê cùng Tony là tập hợp những bài viết truyền cảm hứng của tác giả Tony Buổi Sáng.",
    pages: 296,
    publisher: "NXB Trẻ",
    publishDate: "2017-06-20",
    language: "Tiếng Việt",
    isbn: "978-604-2-34567-8",
    genres: ["Kỹ năng sống", "Văn học", "Truyền cảm hứng"],
  },
  {
    id: 7,
    title: "Tôi Thấy Hoa Vàng Trên Cỏ Xanh",
    author: "Nguyễn Nhật Ánh",
    price: 105000,
    originalPrice: 125000,
    rating: 4.8,
    reviews: 1890,
    image: "/book-cover-yellow-flowers.jpg",
    category: "Văn học",
    inStock: true,
    description: "Tôi thấy hoa vàng trên cỏ xanh là một tác phẩm văn học đầy cảm xúc của nhà văn Nguyễn Nhật Ánh.",
    pages: 368,
    publisher: "NXB Trẻ",
    publishDate: "2010-12-01",
    language: "Tiếng Việt",
    isbn: "978-604-2-11111-1",
    genres: ["Văn học", "Tiểu thuyết", "Tuổi thơ"],
  },
  {
    id: 8,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: 165000,
    originalPrice: 200000,
    rating: 4.7,
    reviews: 1120,
    image: "/thinking-fast-slow-cover.png",
    category: "Tâm lý học",
    inStock: true,
    description: "Trong cuốn sách này, Daniel Kahneman giải thích hai hệ thống định hình cách chúng ta suy nghĩ.",
    pages: 499,
    publisher: "NXB Thế Giới",
    publishDate: "2019-04-10",
    language: "Tiếng Việt",
    isbn: "978-604-2-88888-8",
    genres: ["Tâm lý học", "Khoa học", "Kinh tế học hành vi"],
  },
]

export function getBookById(id) {
  const numId = typeof id === "string" ? Number.parseInt(id, 10) : id
  return BOOKS.find((book) => book.id === numId)
}

export function formatPrice(price) {
  return new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
    minimumFractionDigits: 0,
  }).format(price)
}
